### ISSUE TITLE
Bot will fail to post to slack if message is too long

### ISSUE THREAD

**Issue by ssian2** [hmcts/slack-help-bot#75]
The Slack Help Bot will error out when posting a ticket to slack if the 'analysis' field is too long. This will presumably also apply to every other field in the ticket as well. There appears to be a character limit of 3000 for every 'text' block imposed by the Bolt API that is not mentioned in the documentation 🙃.

Range checks need to be implemented to the bot before it sends the message to slack. I believe the simplest option will simply be to simply cut fields off after 3000 characters and maybe put in a '…' character to indicate it's been truncated. The JIRA API does not appear to impose a similar limit that I know of (if it does, it's much higher), so untruncated fields can probably be posted to JIRA just fine, that way we shouldn't lose any information when posting.

Logs from the error when it cropped up earlier today:

```
[ERROR]  bolt-app failed to match all allowed schemas [json-pointer:/blocks/1/text]
[ERROR]  bolt-app must be less than 3001 characters [json-pointer:/blocks/1/text/text]
[ERROR]  bolt-app Error: An API error occurred: invalid_blocks
    at platformErrorFromResult (/opt/app/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/opt/app/node_modules/@slack/web-api/dist/WebClient.js:167:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async execute (/opt/app/app.js:255:26)
    at async processStepMiddleware (/opt/app/node_modules/@slack/bolt/dist/WorkflowStep.js:96:9)
    at async Array.<anonymous> (/opt/app/node_modules/@slack/bolt/dist/conversation-store.js:67:9)
    at async Array.<anonymous> (/opt/app/node_modules/@slack/bolt/dist/middleware/builtin.js:262:9)
    at async App.processEvent (/opt/app/node_modules/@slack/bolt/dist/App.js:536:13)
    at async SocketModeClient.<anonymous> (/opt/app/node_modules/@slack/bolt/dist/receivers/SocketModeReceiver.js:146:13) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_blocks',
    errors: [
      'failed to match all allowed schemas [json-pointer:/blocks/1/text]',
      'must be less than 3001 characters [json-pointer:/blocks/1/text/text]'
    ],
    response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
  }
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: An API error occurred: invalid_blocks
    at platformErrorFromResult (/opt/app/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/opt/app/node_modules/@slack/web-api/dist/WebClient.js:167:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async execute (/opt/app/app.js:255:26)
    at async processStepMiddleware (/opt/app/node_modules/@slack/bolt/dist/WorkflowStep.js:96:9)
    at async Array.<anonymous> (/opt/app/node_modules/@slack/bolt/dist/conversation-store.js:67:9)
    at async Array.<anonymous> (/opt/app/node_modules/@slack/bolt/dist/middleware/builtin.js:262:9)
    at async App.processEvent (/opt/app/node_modules/@slack/bolt/dist/App.js:536:13)
    at async SocketModeClient.<anonymous> (/opt/app/node_modules/@slack/bolt/dist/receivers/SocketModeReceiver.js:146:13) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_blocks',
    errors: [
      'failed to match all allowed schemas [json-pointer:/blocks/1/text]',
      'must be less than 3001 characters [json-pointer:/blocks/1/text/text]'
    ],
    response_metadata: {
      messages: [
        '[ERROR] failed to match all allowed schemas [json-pointer:/blocks/1/text]',
        '[ERROR] must be less than 3001 characters [json-pointer:/blocks/1/text/text]'
      ],
      scopes: [
        'app_mentions:read',
        'channels:history',
        'commands',
        'chat:write',
        'chat:write.customize',
        'users.profile:read',
        'users:read',
        'users:read.email',
        'workflow.steps:execute',
        'reactions:write'
      ],
      acceptedScopes: [ 'chat:write' ]
    }
  }
}
```

**Comment by timja** [comment]
You could also split it and post it into comments? so all the context is in slack?

ideally you don't need to go to Jira
